name: kod_kraiona
description: "Код Крайона українська версія"


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0  # Библиотека для инициализации и использования сервисов Firebase в приложении.
  gsheets: ^0.4.2  # Библиотека для работы с Google Sheets (Таблицами Google) через API.
  http: ^0.13.3  # Библиотека для выполнения HTTP-запросов (например, для отправки и получения данных через REST API).
  #async: ^2.8.2  # Библиотека, содержащая дополнительные утилиты для работы с асинхронными операциями в Dart.
  logging: ^1.0.2  # Библиотека для ведения логирования в приложении, чтобы отслеживать события и ошибки.
  flutter_bloc: ^8.1.3  # Библиотека для управления состоянием приложения с использованием BLoC (Business Logic Component) паттерна.
  equatable: ^2.0.5  # Библиотека, которая облегчает сравнение объектов по значениям их полей, используется вместе с `flutter_bloc`.
  shared_preferences: ^2.0.15  # Библиотека для работы с локальным хранилищем (например, для сохранения настроек приложения или данных пользователя).
  package_info_plus: ^3.0.0
  connectivity_plus: ^3.0.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/main_image.jpg
    - assets/credentials/credentials.json


  uses-material-design: true
