name: Build and Deploy

on:
  push:
    branches:
      - main  # Запускаем сборку и деплой при пуше в основную ветку

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.0'

      - name: Create credentials.json
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KOD_KRAIONA }}" > assets/credentials/credentials.json

      - name: Get Flutter packages
        run: flutter pub get

      - name: Build the web app
        run: flutter build web

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
