name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Create credentials directory
        run: mkdir -p assets/credentials

      - name: Create credentials.json
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KOD_KRAIONA }}" > assets/credentials/credentials.json

      - name: Get Flutter packages
        run: flutter pub get

      - name: Build the web app
        run: flutter build web

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KOD_KRAIONA }}
          channelId: live
          projectId: kod-kraiona
